variables:
  USE_ISORT: "false"
  USE_FLAKE: "false"
  USE_PRE_COMMIT: "true"
  PKG_COVERAGE: "karabo.utidserver"
  DOC_DIRECTORY: docs

include:
  - project: karabo/gitlabci
    file: .python-ci.yml
    ref: main
  - project: karabo/gitlabci
    file: .pages-markdown-ci.yml
    ref: main

pytest:
  parallel:
    matrix:
      - ARCH_TAG:   ["redhat-9-004"]
        KARABO_TAG: ["2.21.2", "latest_prerelease_build"]
